apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-web
  template:
    metadata:
      labels:
        app: micro-web
    spec:
      containers:
        - name: micro-web
          image: micro/micro:v2.9.3
          imagePullPolicy: Always
          args:
            - web
          env:
            - name: MICRO_REGISTRY
              value: "mdns"
            - name: MICRO_WEB_ADDRESS
              value: ":8082"
          ports:
            - containerPort: 8082
              name: web-port
