apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      serviceAccountName: micro-services
      containers:
        - name: file-service
          image: gcr.io/fleet-271114/fleet-file-service
          imagePullPolicy: Always
          command:
            ["./file-service", "--selector=static", "--server_address=:8080"]
          envFrom:
          - configMapRef:
              name: pod-base-env
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: file-service-secrets
                  key: REDIS_URL
          ports:
            - containerPort: 8080