version: '3.7'

services:
  microapigateway:
    image: micro/micro
    command: api --handler=rpc --address=:8080
    ports:
      - "8080:8080"
    environment:
      MICRO_REGISTRY: "mdns"
  
  microweb:
    image: micro/micro
    command: web
    ports:
      - "8081:8081"
    environment:
      MICRO_WEB_ADDRESS: ":8081"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    hostname: redis
    volumes:
      - redis-data:/data # ensures data persistence between restarting
    ports:
      - "6379:6379"

  file-service:
    restart: always
    build: ./file-service
    depends_on:
      - redis
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
  
  test-run-service:
    restart: always
    build: ./test-run-service
    depends_on:
      - pg-database
      - file-service
    links:
      - pg-database
    environment:
      MICRO_SERVER_ADDRESS: ":50051"

  storage-uploader-service:
    restart: always
    build: ./storage-uploader-service
    environment:
      MICRO_SERVER_ADDRESS: ":50051"

  run-controller-service:
    restart: always
    build: ./run-controller-service
    environment:
      MICRO_SERVER_ADDRESS: ":50051"

  pg-database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

volumes:
  redis-data: