apiVersion: apps/v1
kind: Deployment
metadata:
  name: wss-deployment
spec:
  selector:
    matchLabels:
      app: wss
  template:
    metadata:
      labels:
        app: wss
    spec:
      containers:
        - name: wss
          image: gcr.io/fleet-271114/fleet-wss
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: wss-port
