// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/test-run-service/test-run-service.proto

package go_micro_service_testrunservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TestRunService service

func NewTestRunServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TestRunService service

type TestRunService interface {
	Create(ctx context.Context, in *TestRun, opts ...client.CallOption) (*TestRun, error)
	GetAll(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*GetAllResponse, error)
}

type testRunService struct {
	c    client.Client
	name string
}

func NewTestRunService(name string, c client.Client) TestRunService {
	return &testRunService{
		c:    c,
		name: name,
	}
}

func (c *testRunService) Create(ctx context.Context, in *TestRun, opts ...client.CallOption) (*TestRun, error) {
	req := c.c.NewRequest(c.name, "TestRunService.Create", in)
	out := new(TestRun)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testRunService) GetAll(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*GetAllResponse, error) {
	req := c.c.NewRequest(c.name, "TestRunService.GetAll", in)
	out := new(GetAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestRunService service

type TestRunServiceHandler interface {
	Create(context.Context, *TestRun, *TestRun) error
	GetAll(context.Context, *EmptyRequest, *GetAllResponse) error
}

func RegisterTestRunServiceHandler(s server.Server, hdlr TestRunServiceHandler, opts ...server.HandlerOption) error {
	type testRunService interface {
		Create(ctx context.Context, in *TestRun, out *TestRun) error
		GetAll(ctx context.Context, in *EmptyRequest, out *GetAllResponse) error
	}
	type TestRunService struct {
		testRunService
	}
	h := &testRunServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TestRunService{h}, opts...))
}

type testRunServiceHandler struct {
	TestRunServiceHandler
}

func (h *testRunServiceHandler) Create(ctx context.Context, in *TestRun, out *TestRun) error {
	return h.TestRunServiceHandler.Create(ctx, in, out)
}

func (h *testRunServiceHandler) GetAll(ctx context.Context, in *EmptyRequest, out *GetAllResponse) error {
	return h.TestRunServiceHandler.GetAll(ctx, in, out)
}
