apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-registry
subjects:
- kind: ServiceAccount
  name: micro-services
roleRef:
  kind: ClusterRole
  name: micro-registry
  apiGroup: rbac.authorization.k8s.io