apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      serviceAccountName: micro-services
      containers:
        - name: file-service
          image: gcr.io/fleet-295921/fleet-file-service
          imagePullPolicy: Always
          command:
            [
              "./service",
              "--selector=static",
              "--server_address=:8080",
              "--broker=googlepubsub",
            ]
          envFrom:
            - configMapRef:
                name: pod-base-env
            - configMapRef:
                name: pubsub-config
          env:              
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: file-service-secrets
                  key: REDIS_URL
          ports:
            - containerPort: 8080
