apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      serviceAccountName: micro-services
      containers:
        - name: file-service
          image: gcr.io/fleet-295921/fleet-file-service
          imagePullPolicy: Always
          command:
            [
              "./service",
              "--selector=static",
              "--server_address=:8080",
            ]
          envFrom:
            - configMapRef:
                name: pod-base-env
          ports:
            - containerPort: 8080
