version: 2
jobs:
  build-file-service-image:
    environment:
      IMAGE_NAME: fleet-file-service
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build $IMAGE_NAME Docker image
          command: docker build -t $IMAGE_NAME:latest ./file-service
  build-test-run-image:
    environment:
      IMAGE_NAME: fleet-test-run
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build $IMAGE_NAME Docker image
          command: docker build -t $IMAGE_NAME:latest ./test-run
workflows:
  version: 2
  build-docker-images:
    jobs:
      - build-file-service-image:
          filters:
            branches:
              only: master
      - build-test-run-image:
          filters:
            branches:
              only: master
