version: 2
jobs:
  # build-file-service-image:
  #   environment:
  #     IMAGE_NAME: fleet-file-service
  #   docker:
  #     - image: circleci/buildpack-deps:stretch
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: Build file-service docker image
  #         command: docker build -t $IMAGE_NAME:latest ./file-service
  # build-test-run-image:
  #   environment:
  #     IMAGE_NAME: fleet-test-run
  #   docker:
  #     - image: circleci/buildpack-deps:stretch
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: Build test-run docker image
  #         command: docker build -t $IMAGE_NAME:latest ./test-run
  upload-images-to-gcloud:
    requires:
      - build-file-service-image 
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Push docker images to GCR
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json && \
              gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
workflows:
  version: 2
  build-docker-images:
    jobs:
      # - build-file-service-image:
      #     filters:
      #       branches:
      #         only: master
      # - build-test-run-image:
      #     filters:
      #       branches:
      #         only: master
      - upload-images-to-gcloud:
          filters:
            branches:
              only: master
