version: 2.1
orbs:
  gcs: t3n/gcs@0.1.3
  gcr: circleci/gcp-gcr@0.8.0
jobs:
  build-push-file-service-image:
    description: Build and push file service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-file-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/file-service
          docker-context: ~/project/file-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-test-run-service-image:
    description: Build and push test run service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-test-run-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/test-run-service
          docker-context: ~/project/test-run-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-storage-uploader-service-image:
    description: Build and push Storage uploader service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-storage-uploader-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/storage-uploader-service
          docker-context: ~/project/storage-uploader-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-user-service-image:
    description: Build and push User service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-user-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/user-service
          docker-context: ~/project/user-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-run-controller-service-image:
    description: Build and push run controller service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-run-controller-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/run-controller-service
          docker-context: ~/project/run-controller-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-wss-image:
    description: Build and push WSS image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-wss
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/wss
          docker-context: ~/project/wss
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-resource-manager-service:
    description: Build and push Resource Manager service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-resource-manager-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/resource-manager-service
          docker-context: ~/project/resource-manager-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  compile-file-builder:
    description: Compile file-builder server executable
    docker:
      - image: circleci/golang:latest
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    environment:
      GO111MODULE: "on"
      GOOS: "linux"
      GOARCH: "amd64"
    steps:
      - checkout
      - run:
          name: Compile code for linux
          command: cd ~/project/file-builder && go build -o ~/project/exec/file-builder -v .
  upload-file-builder :
    description: Upload file-builder server executable to GCS
    machine: true
    environment:
      BUCKET_NAME: "fleet-deploy-binaries"
    steps:
      - gcs/gcs-auth
      - gcs/rsync:
          bucket: $BUCKET_NAME
          source: ~/project/exec/
workflows:
  compile_and_upload_file_builder_exec:
    jobs:
      - compile-file-builder
      - upload-file-builder

#  build_and_upload_service_images:
#    jobs:
#      - build-push-file-service-image:
#          filters:
#            branches:
#              only: master
#      - build-push-test-run-service-image:
#          filters:
#            branches:
#              only: master
#      - build-push-storage-uploader-service-image:
#          filters:
#            branches:
#              only: master
#      - build-push-user-service-image:
#          filters:
#            branches:
#              only: master
#      - build-push-run-controller-service-image:
#          filters:
#            branches:
#              only: master
#      - build-push-wss-image:
#          filters:
#            branches:
#              only: master
#      - build-push-resource-manager-service:
#          filters:
#            branches:
#              only: master
