version: 2.1
orbs:
  gcr: circleci/gcp-gcr@0.8.0
jobs:
  build-push-file-service-image:
    description: Build and push file service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-file-service
      WORKDIR: ~/project/file-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: {$WORKDIR}
          docker-context: ${WORKDIR}
          image: $IMAGE_NAME
          tag: $CIRCLE_SHA1
      - gcr/push-image:
          image: $IMAGE_NAME
          tag: $CIRCLE_SHA1
  build-push-test-run-image:
    description: Build and push test run service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-test-run
      WORKDIR: ~/project/test-run
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ${WORKDIR}
          docker-context: ${WORKDIR}
          image: $IMAGE_NAME
          tag: $CIRCLE_SHA1
      - gcr/push-image:
          image: $IMAGE_NAME
          tag: $CIRCLE_SHA1
workflows:
  build_and_upload_service_images:
    jobs:
      - build-push-file-service-image:
          filters:
            branches:
              only: master
      - build-push-test-run-image:
          filters:
            branches:
              only: master