version: 2.1
orbs:
  gcr: circleci/gcp-gcr@0.8.0
jobs:
  build-push-file-service-image:
    description: Build and push file service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-file-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/file-service
          docker-context: ~/project/file-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-test-run-service-image:
    description: Build and push test run service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-test-run-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/test-run-service
          docker-context: ~/project/test-run-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-storage-uploader-service-image:
    description: Build and push Storage uploader service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-storage-uploader-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/storage-uploader-service
          docker-context: ~/project/storage-uploader-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
  build-push-user-service-image:
    description: Build and push User service image to GCR
    machine: true
    environment:
      IMAGE_NAME: fleet-user-service
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          path: ~/project/user-service
          docker-context: ~/project/user-service
          image: $IMAGE_NAME
      - gcr/push-image:
          image: $IMAGE_NAME
workflows:
  build_and_upload_service_images:
    jobs:
      - build-push-file-service-image:
          filters:
            branches:
              only: master
      - build-push-test-run-service-image:
          filters:
            branches:
              only: master
      - build-push-storage-uploader-service-image:
          filters:
            branches:
              only: master
      - build-push-user-service-image:
          filters:
            branches:
              only: master
    
