version: 2
jobs:
  build-file-service-image:
    working_directory: ../file-service
    environment:
      IMAGE_NAME: fleet-file-service
    docker: 
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build $IMAGE_NAME Docker image
          command: docker build -t $IMAGE_NAME:latest .
  build-test-run-image:
    working_directory: ../test-run
    environment:
      IMAGE_NAME: fleet-test-run
    docker: 
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build $IMAGE_NAME Docker image
          command: docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-docker-images:
    jobs:
      - build-file-service:
          filters:
            branches: 
              only: master