"SERVICE_NAME": "go.micro.api.resource-manager-service"
"DB_HOST": "127.0.0.1"
"DB_USER": "postgres"
"DB_NAME": "fleet"
"DB_PASSWORD": "root"
"GOOGLE_PROJECT_ID": "fleet-271114"
"FS_DEPLOY_LOCATIONS": "us-central1-a"