apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: micro-services
      containers:
      - name: user-service
        image: gcr.io/fleet-271114/fleet-user-service
        imagePullPolicy: Always
        command: [
          "./service",
          "--selector=static",
          "--server_address=:8080",
          "--broker=googlepubsub"
        ]
        envFrom:
          - configMapRef:
              name: pod-base-env
          - secretRef:
              name: user-service-secrets
        ports:
        - containerPort: 8080