apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: micro-api
  template:
    metadata:
      labels:
        app: micro-api
    spec:
      containers:
        - name: micro-api
          image: micro/micro:v2.9.3
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
          imagePullPolicy: Always
          args:
            - api
            - --handler=rpc
          env:
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: "etcd"
            - name: MICRO_API_ADDRESS
              value: ":80"
          ports:
            - containerPort: 80
              name: api-port