// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/run-controller-service/run-controller-service.proto

package go_micro_api_runControllerService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RunControllerService service

func NewRunControllerServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RunControllerService service

type RunControllerService interface {
}

type runControllerService struct {
	c    client.Client
	name string
}

func NewRunControllerService(name string, c client.Client) RunControllerService {
	return &runControllerService{
		c:    c,
		name: name,
	}
}

// Server API for RunControllerService service

type RunControllerServiceHandler interface {
}

func RegisterRunControllerServiceHandler(s server.Server, hdlr RunControllerServiceHandler, opts ...server.HandlerOption) error {
	type runControllerService interface {
	}
	type RunControllerService struct {
		runControllerService
	}
	h := &runControllerServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RunControllerService{h}, opts...))
}

type runControllerServiceHandler struct {
	RunControllerServiceHandler
}
