// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/test-run/test-run.proto

package go_micro_service_testrun

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TestRun service

func NewTestRunEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TestRun service

type TestRunService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TestRun_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (TestRun_PingPongService, error)
}

type testRunService struct {
	c    client.Client
	name string
}

func NewTestRunService(name string, c client.Client) TestRunService {
	return &testRunService{
		c:    c,
		name: name,
	}
}

func (c *testRunService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TestRun.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testRunService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TestRun_StreamService, error) {
	req := c.c.NewRequest(c.name, "TestRun.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &testRunServiceStream{stream}, nil
}

type TestRun_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type testRunServiceStream struct {
	stream client.Stream
}

func (x *testRunServiceStream) Close() error {
	return x.stream.Close()
}

func (x *testRunServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *testRunServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *testRunServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *testRunServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testRunService) PingPong(ctx context.Context, opts ...client.CallOption) (TestRun_PingPongService, error) {
	req := c.c.NewRequest(c.name, "TestRun.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &testRunServicePingPong{stream}, nil
}

type TestRun_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type testRunServicePingPong struct {
	stream client.Stream
}

func (x *testRunServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *testRunServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *testRunServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *testRunServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *testRunServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *testRunServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TestRun service

type TestRunHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, TestRun_StreamStream) error
	PingPong(context.Context, TestRun_PingPongStream) error
}

func RegisterTestRunHandler(s server.Server, hdlr TestRunHandler, opts ...server.HandlerOption) error {
	type testRun interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type TestRun struct {
		testRun
	}
	h := &testRunHandler{hdlr}
	return s.Handle(s.NewHandler(&TestRun{h}, opts...))
}

type testRunHandler struct {
	TestRunHandler
}

func (h *testRunHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TestRunHandler.Call(ctx, in, out)
}

func (h *testRunHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TestRunHandler.Stream(ctx, m, &testRunStreamStream{stream})
}

type TestRun_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type testRunStreamStream struct {
	stream server.Stream
}

func (x *testRunStreamStream) Close() error {
	return x.stream.Close()
}

func (x *testRunStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *testRunStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *testRunStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *testRunStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *testRunHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TestRunHandler.PingPong(ctx, &testRunPingPongStream{stream})
}

type TestRun_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type testRunPingPongStream struct {
	stream server.Stream
}

func (x *testRunPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *testRunPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *testRunPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *testRunPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *testRunPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *testRunPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
