apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-run
spec:
  selector:
    matchLabels:
      app: test-run
  template:
    metadata:
      labels:
        app: test-run
    spec:
      serviceAccountName: micro-services
      containers:
      - name: test-run
        image: gcr.io/fleet-271114/fleet-test-run
        imagePullPolicy: Always
        command: [
          "./test-run",
          "--selector=static",
          "--server_address=:8080"
        ]
        env:
            - name: ENV_NAME
              value: "prod"
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: "etcd-client"
        ports:
        - containerPort: 8080